### ISSUE TITLE
README.md is improperly rendered as raw HTML

### ISSUE THREAD

**Issue by Atry** [scalacenter/scaladex#463]
![screen shot 2017-07-14 at 09 51 25](https://user-images.githubusercontent.com/601530/28194985-3eaf65e0-687a-11e7-8d9d-9e99be6349a3.png)

**Comment by heathermiller** [comment]
Looks OK for me. Indeed I see the HTML rendering (as you have shown) for maybe some milliseconds before the HTML is properly rendered. But as soon as the page is finished loading it looks like this for me:

<img width="1274" alt="screen shot 2017-07-14 at 9 32 52 am" src="https://user-images.githubusercontent.com/687163/28202850-74ef15cc-6877-11e7-9158-023bfa0c0ecd.png">

**Comment by heathermiller** [comment]
(The images aren't loading, which @MasseGuillaume knows about and will fix soon, I'm sure)

**Comment by Atry** [comment]
Have a look at the HTML source of the Scaladex page, then you will see the README.md is rendered as "one character per line".

**Comment by MasseGuillaume** [comment]
@Atry is hiting the api Githu api limit this is why the result is different. The fallback is the Readme from the server. The readme from the server was not read correctly, I need to reindex.

**Comment by MichaelViveros** [comment]
@MasseGuillaume Has #451 been deployed? That should fix it

**Comment by holograph** [comment]
The issue strikes again; see https://index.scala-lang.org/wix/accord/accord-api, right now it shows raw markdown - not limited to just images...

**Comment by MasseGuillaume** [comment]
Now fixed, thanks @MichaelViveros !

**Comment by MasseGuillaume** [comment]
ops, I closed this one to quickly. If I disable javascript I still see the issue.

**Comment by holograph** [comment]
In my case, it happens about 50% of the time (usually consistent for any given session)

**Comment by MasseGuillaume** [comment]
@holograph if you login with GitHub it should work 100% of the time.

**Comment by holograph** [comment]
@MasseGuillaume I'm more worried about potential users that aren't very likely to be logged in :-)

**Comment by heathermiller** [comment]
@MasseGuillaume what's the deal with falling back to the server when the API limit is reached?

**Comment by MasseGuillaume** [comment]
@heathermiller taking a look
